enable crs_run to re-read credentials on every run so that they can be changed without restarting the script
git-svn-id: https://subversion.fem.tu-ilmenau.de/repository/cccongress/trunk@1262 8a601fa4-19c6-4598-94e3-4e3ea6015ade

diff --git a/bin/crs_run b/bin/crs_run
--- a/bin/crs_run
+++ b/bin/crs_run
@@ -1,21 +1,5 @@
 #!/bin/bash
 
-CONFIGFILE=/etc/default/crs-worker
-
-if [ -r "${CONFIGFILE}" ] ; then
-    . "${CONFIGFILE}"
-fi
-
-export CRS_SECRET=${CRS_SECRET:-$DEFAULT_CRS_SECRET}
-export CRS_TOKEN=${CRS_TOKEN:-$DEFAULT_CRS_TOKEN}
-export CRS_TRACKER=${CRS_TRACKER:-$DEFAULT_CRS_TRACKER}
-export HTTPS_CA_DIR=${HTTPS_CA_DIR:-/etc/ssl/certs}
-
-if [ -z "${CRS_SECRET}" -o -z "${CRS_TOKEN}" -o -z "${CRS_TRACKER}" ]; then
-    echo "CRS_SECRET, CRS_TOKEN and/or CRS_TRACKER not set. aborting.";
-    exit 1;
-fi
-
 SCRIPT_NAME=`basename "$1"`
 if [ -z "${SCRIPT_NAME}" ]; then 
     echo "no script given."
@@ -23,10 +7,7 @@ if [ -z "${SCRIPT_NAME}" ]; then
     exit 1
 fi
 
-SLEEP_TIME=${2:-30}
-if [ -z "${SLEEP_TIME}" ]; then 
-    SLEEP_TIME=30
-fi
+SLEEP_TIME=${SLEEP_TIME:-30}
 
 # short sleep time after work has done
 SLEEP_TIME_SHORT=2
@@ -48,14 +29,6 @@ export PERL5LIB=${SCRIPT_PATH}/lib
 # assemble script command
 SCRIPT=${SCRIPT_PATH}/scripts/${SCRIPT_NAME}
 
-if [ ! -f "${SCRIPT}" ]; then
-    echo "selected script (${SCRIPT}) does not exist";
-fi
-
-if [ ! -x "${SCRIPT}" ]; then
-    echo "selected script (${SCRIPT}) is not executable";
-fi
-
 echo "-------------------------------------------"
 echo "       CRS Runner v1.0 by FeM 2016"
 echo "-------------------------------------------"
@@ -64,13 +37,47 @@ echo "Sleep time:  ${SLEEP_TIME}s"
 echo "Started on:  $(date +%c)"
 echo "-------------------------------------------"
 
+##### BEGIN WHILE LOOP #####
 while true; do
+
+CONFIGFILE=/etc/default/crs-worker
+
+if [ -r "${CONFIGFILE}" ] ; then
+    . "${CONFIGFILE}"
+fi
+if [ -n "$2" -a -r "$2" ] ; then
+    . "$2"
+fi
+
+export CRS_SECRET=${CRS_SECRET:-$DEFAULT_CRS_SECRET}
+export CRS_TOKEN=${CRS_TOKEN:-$DEFAULT_CRS_TOKEN}
+export CRS_TRACKER=${CRS_TRACKER:-$DEFAULT_CRS_TRACKER}
+export HTTPS_CA_DIR=${HTTPS_CA_DIR:-/etc/ssl/certs}
+
+if [ -z "${CRS_SECRET}" -o -z "${CRS_TOKEN}" -o -z "${CRS_TRACKER}" ]; then
+    echo "CRS_SECRET, CRS_TOKEN and/or CRS_TRACKER not set. aborting.";
+    exit 1;
+fi
+
+if [ ! -f "${SCRIPT}" ]; then
+    echo "selected script (${SCRIPT}) does not exist";
+    sleep ${SLEEP_TIME_LONG}
+    continue
+fi
+
+if [ ! -x "${SCRIPT}" ]; then
+    echo "selected script (${SCRIPT}) is not executable";
+    sleep ${SLEEP_TIME_LONG}
+    continue
+fi
+
+
     echo "------- executing ($(date +%X)) ---------"
     "${SCRIPT}"
     if [ $? -eq 250 ]; then
         echo "---- got termination signal, exiting ----"
         sleep 30
-        exit 0;
+        break;
     fi
     if [ $? -eq 100 ]; then
         echo "------- waiting (short) ${SLEEP_TIME_SHORT}s ($(date +%X)) ---------"
@@ -83,4 +90,6 @@ while true; do
             sleep ${SLEEP_TIME}
         fi
     fi
+
 done
+##### END WHILE LOOP #####
