whitespace fixes, intentionally separated from preceding commit
git-svn-id: https://subversion.fem.tu-ilmenau.de/repository/cccongress/trunk@1263 8a601fa4-19c6-4598-94e3-4e3ea6015ade

diff --git a/bin/crs_run b/bin/crs_run
--- a/bin/crs_run
+++ b/bin/crs_run
@@ -40,37 +40,36 @@ echo "-------------------------------------------"
 ##### BEGIN WHILE LOOP #####
 while true; do
 
-CONFIGFILE=/etc/default/crs-worker
+    CONFIGFILE=/etc/default/crs-worker
 
-if [ -r "${CONFIGFILE}" ] ; then
-    . "${CONFIGFILE}"
-fi
-if [ -n "$2" -a -r "$2" ] ; then
-    . "$2"
-fi
+    if [ -r "${CONFIGFILE}" ] ; then
+        . "${CONFIGFILE}"
+    fi
+    if [ -n "$2" -a -r "$2" ] ; then
+        . "$2"
+    fi
 
-export CRS_SECRET=${CRS_SECRET:-$DEFAULT_CRS_SECRET}
-export CRS_TOKEN=${CRS_TOKEN:-$DEFAULT_CRS_TOKEN}
-export CRS_TRACKER=${CRS_TRACKER:-$DEFAULT_CRS_TRACKER}
-export HTTPS_CA_DIR=${HTTPS_CA_DIR:-/etc/ssl/certs}
+    export CRS_SECRET=${CRS_SECRET:-$DEFAULT_CRS_SECRET}
+    export CRS_TOKEN=${CRS_TOKEN:-$DEFAULT_CRS_TOKEN}
+    export CRS_TRACKER=${CRS_TRACKER:-$DEFAULT_CRS_TRACKER}
+    export HTTPS_CA_DIR=${HTTPS_CA_DIR:-/etc/ssl/certs}
 
-if [ -z "${CRS_SECRET}" -o -z "${CRS_TOKEN}" -o -z "${CRS_TRACKER}" ]; then
-    echo "CRS_SECRET, CRS_TOKEN and/or CRS_TRACKER not set. aborting.";
-    exit 1;
-fi
+    if [ -z "${CRS_SECRET}" -o -z "${CRS_TOKEN}" -o -z "${CRS_TRACKER}" ]; then
+        echo "CRS_SECRET, CRS_TOKEN and/or CRS_TRACKER not set. aborting.";
+        exit 1;
+    fi
 
-if [ ! -f "${SCRIPT}" ]; then
-    echo "selected script (${SCRIPT}) does not exist";
-    sleep ${SLEEP_TIME_LONG}
-    continue
-fi
+    if [ ! -f "${SCRIPT}" ]; then
+        echo "selected script (${SCRIPT}) does not exist";
+        sleep ${SLEEP_TIME_LONG}
+        continue
+    fi
 
-if [ ! -x "${SCRIPT}" ]; then
-    echo "selected script (${SCRIPT}) is not executable";
-    sleep ${SLEEP_TIME_LONG}
-    continue
-fi
-
+    if [ ! -x "${SCRIPT}" ]; then
+        echo "selected script (${SCRIPT}) is not executable";
+        sleep ${SLEEP_TIME_LONG}
+        continue
+    fi
 
     echo "------- executing ($(date +%X)) ---------"
     "${SCRIPT}"
